### PR TITLE
Update ko_kr translation

### PR DESCRIPTION
**Pull request by gisellevonbingen**
Tried refined the sentences naturally.
Thanks. :heart:

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Hello, can you rebase your branch on the latest version of develop please?

**Comment by gisellevonbingen** [comment]
Did you mean like this?

image

**Comment by raoulvdberge** [comment]
Hello, yes, please check the failed checks.
- Please fix the commit message format (rename commit)
- Please add a changelog entry.

**Comment by raoulvdberge** [comment]
Unfortunately, merge commits aren't allowed. Please rebase

**Comment by raoulvdberge** [comment]
Also, don't link github issue numbers in the changelog.

**Comment by gisellevonbingen** [comment]
Oops.. i see..

**Comment by gisellevonbingen** [comment]
Changed

**Comment by raoulvdberge** [comment]
You updated the wrong changelog entry. It has to be under "Unreleased", not under an already released version

**Comment by gisellevonbingen** [comment]
Oh, you right.

**Comment by raoulvdberge** [comment]
And now just add a heading (`### Changed`) and it's complete.

**Comment by gisellevonbingen** [comment]
yes it done.

**Comment by raoulvdberge** [comment]
Thanks!

**Pull request merged**
